### ISSUE TITLE
hi i got an error

### ISSUE THREAD

**Issue by ivannetta** [legend-js-dev/ModMail-Bot#1]
im hosting bot on replit and i get this error

 npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/ModMail-Bot/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/ModMail-Bot/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-03T06_20_40_948Z-debug.log
exit status 254

**Comment by insidiousthedev** [comment]
there is no package.json file
try making a `package.json` file first, do `npm install` and then run it

**Comment by vibenOfficial** [comment]
nah man just type npm init and follow the instructions.. also there is no intents
